---
name: Syntax Tests

on: [push, pull_request]

jobs:
  syntax_tests:
    name: Syntax Tests (${{ matrix.build }})
    strategy:
      matrix:
        include:
          - build: latest  # This is the default
          - build: 3210  # Latest known ST3 build with a test binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          package_name: Zeek
